spring:
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    hibernate:
      ddl-auto: ${DDL-AUTO-MODE}
  datasource:
#    url: jdbc:postgresql://host.docker.internal:31032/hotel_auth_db_data?ssl=false
#    url: jdbc:postgresql://localhost:5433/hotel_auth_db_data?ssl=false
    url: ${DB_AUTH_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    hikari:
      connection-timeout: 50000
      maximum-pool-size: 100
      idle-timeout: 60000           # 1 ??????
      max-lifetime: 30000