spring:
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://host.docker.internal:31032/hotel_auth_db_data?ssl=false
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 50000
      maximum-pool-size: 100
      idle-timeout: 60000           # 1 ??????
      max-lifetime: 30000