spring:
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5433/hotel_auth_db_data?ssl=false
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 500000
      maximum-pool-size: 10000
      idle-timeout: 600000             # 1 ??????
      max-lifetime: 3000000