version: '3.8'

services:
  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotel_auth_db_data
    command: >
      postgres -c max_connections=10000
#    networks:
#      default:
#        ipv4_address: 172.20.0.100
#
#networks:
#  default:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.20.0.0/16