apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.name }}-service
  labels:
    app: {{ .Values.postgresql.name }}
    component: database
spec:
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.port }}
      protocol: TCP
  selector:
    app: {{ .Values.postgresql.name }}
  type: {{ .Values.postgresql.service.type }}